import { pickEnvKeys, optionalStringShape, type EnvValidationResult } from './shared.js'

const IW_SITE_Q2_ENV_KEYS = [
  'ANTHROPIC_API_KEY',
  'CAL_API_BASE',
  'CAL_API_KEY',
  'CAL_BOOKING_MANAGE_URL_BASE',
  'CAL_EVENT_TYPE_ID',
  'CAL_ORGANIZATION_SLUG',
  'CONTACT_BYPASS_RECAPTCHA_SECRET',
  'CONTACT_EMAIL',
  'CONTACT_INSECURE_SKIP_RECAPTCHA',
  'CONTACT_INTEGRATION_DEBUG',
  'GOOGLE_APPLICATION_CREDENTIALS',
  'GOOGLE_APPLICATION_CREDENTIALS_JSON',
  'HUBSPOT_ACCESS_TOKEN',
  'HUBSPOT_CONTACT_KICKOFF_CAL_UID_PROPERTY',
  'HUBSPOT_CONTACT_KICKOFF_START_PROPERTY',
  'HUBSPOT_DEAL_KICKOFF_CAL_UID_PROPERTY',
  'HUBSPOT_DEAL_KICKOFF_START_PROPERTY',
  'HUBSPOT_DEAL_OWNER_ID',
  'HUBSPOT_DEAL_PIPELINE_ID',
  'HUBSPOT_DEAL_STAGE_LEAD_QUALIFIED',
  'HUBSPOT_FORM_GUID',
  'HUBSPOT_WEBSITE_INTAKE_JSON_PROPERTY',
  'HUBSPOT_WEBSITE_INTAKE_PLAIN_PROPERTY',
  'KICKOFF_BOOKING_JWT_SECRET',
  'KICKOFF_BOOKING_JWT_TTL_SEC',
  'MARKETING_N8N_WEBHOOK_SECRET',
  'MARKETING_N8N_WEBHOOK_SECRET_HEADER',
  'N8N_CONTACT_DEAL_STAGE',
  'N8N_CONTACT_WEBHOOK_URL',
  'N8N_KICKOFF_BOOKED_WEBHOOK_URL',
  'N8N_WEBHOOK_SECRET',
  'N8N_WEBHOOK_SECRET_HEADER',
  'N8N_WEBHOOK_TIMEOUT_MS',
  'NEXT_PUBLIC_ACCOUNTS_URL',
  'NEXT_PUBLIC_CAL_KICKOFF_CAL_LINK',
  'NEXT_PUBLIC_GA_ID',
  'NEXT_PUBLIC_HUBSPOT_ID',
  'NEXT_PUBLIC_RECAPTCHA_SITE_KEY',
  'NEXT_PUBLIC_SCHEDULE_URL',
  'NEXT_PUBLIC_SITE_URL',
  'NODE_ENV',
  'RECAPTCHA_DEBUG_RESPONSE',
  'RECAPTCHA_ENTERPRISE_PROJECT_ID',
  'RECAPTCHA_ENTERPRISE_SITE_KEY',
  'RECAPTCHA_MIN_SCORE',
  'RECAPTCHA_SKIP_IN_DEV',
  'RESEND_API_KEY',
  'WEBSITE_INTAKE_BYPASS_RECAPTCHA_SECRET',
  'WEBSITE_INTAKE_DEBUG_UPSTREAM',
  'WEBSITE_INTAKE_STRICT_N8N',
] as const

const iwSiteQ2EnvSchema = optionalStringShape(IW_SITE_Q2_ENV_KEYS)

export type IwSiteQ2Env = Record<(typeof IW_SITE_Q2_ENV_KEYS)[number], string | undefined>

export function validateIwSiteQ2Env(
  env: NodeJS.ProcessEnv = process.env,
): EnvValidationResult<IwSiteQ2Env> {
  const picked = pickEnvKeys(env, IW_SITE_Q2_ENV_KEYS)
  const result = iwSiteQ2EnvSchema.safeParse(picked)
  if (result.success) {
    return { success: true, data: result.data as IwSiteQ2Env }
  }
  return { success: false, errors: result.error.flatten() }
}
